//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvidxBDDFramework {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Output : global::System.Configuration.ApplicationSettingsBase {
        
        private static Output defaultInstance = ((Output)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Output())));
        
        public static Output Default {
            get {
                return defaultInstance;
            }
        }
    }
}
